### ISSUE TITLE
Extension marked as unsage by Chrome web store

### ISSUE THREAD

**Issue by pmahony893** [matiascamiletti/XML-RPC-Client--Chrome-Extension-#1]
This extension has been marked unsafe by the Chrome web store, and is not available to use.

Is this extension unsafe? 🙁 

![image](https://user-images.githubusercontent.com/32841410/179471151-bce95baf-40e8-4826-b71a-0724e2bdc4a2.png)

**Comment by matiascamiletti** [comment]
@pmahony893 Hi how are you?  This extension is from 11 years ago, it is very likely that it is not safe to use it.
